{
 "title": "Colab stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "colab_GPU_mem_util_percentage" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "colab_RAM_used_percentage" }
   ]
  },
  {
   "title": "GDrive fetchig duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fetching_duration_bucket{le!=\"+Inf\", le!=\"10.0\"}",
     "legendFormat": "<{{le}}s"
    }
   ]
  },
  {
   "title": "GPU free memory (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "colab_GPU_mem_free", "legendFormat": "GPU_MEM" }
   ]
  },
  {
   "title": "GPU used memory (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "colab_GPU_mem_used", "legendFormat": "GPU_MEM" }
   ]
  }
 ]
}